#pragma once

#include <cstdint>

using Dword = std::uint32_t;

enum class ErrCode : int
{
	ERRCODE_UNKNOWN = -1,
	ERRCODE_NONE = 0,
	ERRCODE_USER_CANCEL,
	ERRCODE_TAB_INVALID_INPUT_FILE,
	ERRCODE_TAB_INVALID_REPORT_FILE,
	ERRCODE_TAB_MALFORMED_INPUT_FILE,
	ERRCODE_TAB_MEMORY_ALLOCATION_FAILURE,
	ERRCODE_ARC_INVALID_INPUT_FILE,
	ERRCODE_ARC_INVALID_REPORT_FILE,
	ERRCODE_ARC_INVALID_OUTPUT_DIR,
	ERRCODE_SARC_MEMORY_ALLOCATION_FAILURE,
	ERRCODE_SARC_MALFORMED_HEADER,
	ERRCODE_SARC_INVALID_TARGET_FILE,


	ERRCODE_SARC_FILE_RECORD_NAME_SIZE_LESS_THAN_MIN,
	ERRCODE_SARC_FILE_RECORD_NAME_SIZE_MORE_THAN_MAX,
	ERRCODE_SARC_FILE_INVALID_OUTPUT_FILE,
	ERRCODE_GEN_DELIMITER_RETRIEVAL_ERROR,
	ERRCODE_GEN_UNABLE_TO_CREATE_DIRECTORY,
	ERRCODE_RIPPER_MORE_THAN_ONE_TAB_FILE,
	ERRCODE_RIPPER_NO_TAB_FILE,
	ERRCODE_RIPPER_INVALID_REPORT_FILE,
	ERRCODE_RIPPER_INAVLID_INPUT_FILE,
	ERRCODE_RIPPER_INAVLID_UNKNOWN_FILE,
};
